name: first_exercise

on: push

jobs:
  first-exercise-job:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check out repo code
        uses: actions/checkout@v3

      - run: echo "$(cat hello_world.txt)"
